pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/BalkundeAkash/Collection-dev.git'
            }
        }

        stage('Build with Maven') {
            steps {
                dir('Java_Collection_UI') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Archive JAR') {
            steps {
                dir('Java_Collection_UI/target') {
                    archiveArtifacts artifacts: '*.jar', fingerprint: true
                }
            }
        }
    }
}
