pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                url: 'https://github.com/BalkundeAkash/Collection-dev.git'
            }
        }

        stage('Build UI Project') {
            steps {
                dir('Java_Collection_UI') {
                    echo "Project folder found successfully!"
                }
            }
        }
    }
}
